### ISSUE TITLE
Submodule Foundation?

### ISSUE THREAD

**Issue by casey-chow** [hackprinceton/static#1]
Thoughts on moving to a submoduled foundation, since this repo already has one submodule?

**Comment by zacharyliu** [comment]
Sure, tried it and it seems to work fine. It does end up downloading a lot of files though since you have to then `git clone` the Foundation repo.

**Comment by zacharyliu** [comment]
Interesting that the language distribution drops from ~90% CSS to ~30% CSS now.
![image](https://cloud.githubusercontent.com/assets/376616/22224757/c154afce-e18d-11e6-85db-4e2604e10e48.png)

**Comment by casey-chow** [comment]
Frameworks, man
